name: CI

on:
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format (check)
        run: npx prettier --check .

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Unit tests
        run: npm run test -- --ci

      - name: Build
        run: npm run build

      - name: E2E smoke (Playwright)
        run: |
          npx playwright install --with-deps
          npm run test:e2e -- --reporter=list
